esb/models/equipment.py
"""Equipment model for the equipment registry."""

from datetime import UTC, datetime

from esb.extensions import db


class Equipment(db.Model):
    """Equipment registry entry."""

    __tablename__ = 'equipment'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False, index=True)
    manufacturer = db.Column(db.String(200), nullable=False)
    model = db.Column(db.String(200), nullable=False)
    area_id = db.Column(
        db.Integer, db.ForeignKey('areas.id'), nullable=False, index=True
    )
    serial_number = db.Column(db.String(200), nullable=True)
    acquisition_date = db.Column(db.Date, nullable=True)
    acquisition_source = db.Column(db.String(200), nullable=True)
    acquisition_cost = db.Column(db.Numeric(10, 2), nullable=True)
    warranty_expiration = db.Column(db.Date, nullable=True)
    description = db.Column(db.Text, nullable=True)
    is_archived = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(
        db.DateTime, nullable=False, default=lambda: datetime.now(UTC)
    )
    updated_at = db.Column(
        db.DateTime,
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )

    # Relationships
    area = db.relationship('Area', backref=db.backref('equipment', lazy='dynamic'))

    def __repr__(self):
        return f'<Equipment {self.name!r}>'

esb/forms/equipment_forms.py
"""Equipment forms for area and equipment management."""

from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms import (
    DateField,
    DecimalField,
    SelectField,
    StringField,
    SubmitField,
    TextAreaField,
)
from wtforms.validators import URL, DataRequired, Length, Optional

from esb.models.document import DOCUMENT_CATEGORIES

FORM_DOCUMENT_CATEGORIES = [('', '-- Select Category --')] + DOCUMENT_CATEGORIES


class AreaCreateForm(FlaskForm):
    """Form for creating a new area."""

    name = StringField('Name', validators=[DataRequired(), Length(max=80)])
    slack_channel = StringField('Slack Channel', validators=[DataRequired(), Length(max=80)])
    submit = SubmitField('Create Area')


class AreaEditForm(FlaskForm):
    """Form for editing an existing area."""

    name = StringField('Name', validators=[DataRequired(), Length(max=80)])
    slack_channel = StringField('Slack Channel', validators=[DataRequired(), Length(max=80)])
    submit = SubmitField('Save Changes')


class EquipmentCreateForm(FlaskForm):
    """Form for creating a new equipment record."""

    name = StringField('Name', validators=[DataRequired(), Length(max=200)])
    manufacturer = StringField('Manufacturer', validators=[DataRequired(), Length(max=200)])
    model = StringField('Model', validators=[DataRequired(), Length(max=200)])
    area_id = SelectField('Area', coerce=int, validators=[DataRequired()])
    serial_number = StringField('Serial Number', validators=[Length(max=200)])
    acquisition_date = DateField('Acquisition Date', validators=[Optional()])
    acquisition_source = StringField('Acquisition Source', validators=[Length(max=200)])
    acquisition_cost = DecimalField('Acquisition Cost', places=2, validators=[Optional()])
    warranty_expiration = DateField('Warranty Expiration', validators=[Optional()])
    description = TextAreaField('Description')
    submit = SubmitField('Create Equipment')


class EquipmentEditForm(FlaskForm):
    """Form for editing an existing equipment record."""

    name = StringField('Name', validators=[DataRequired(), Length(max=200)])
    manufacturer = StringField('Manufacturer', validators=[DataRequired(), Length(max=200)])
    model = StringField('Model', validators=[DataRequired(), Length(max=200)])
    area_id = SelectField('Area', coerce=int, validators=[DataRequired()])
    serial_number = StringField('Serial Number', validators=[Length(max=200)])
    acquisition_date = DateField('Acquisition Date', validators=[Optional()])
    acquisition_source = StringField('Acquisition Source', validators=[Length(max=200)])
    acquisition_cost = DecimalField('Acquisition Cost', places=2, validators=[Optional()])
    warranty_expiration = DateField('Warranty Expiration', validators=[Optional()])
    description = TextAreaField('Description')
    submit = SubmitField('Save Changes')


class DocumentUploadForm(FlaskForm):
    """Form for uploading a document to an equipment record."""

    file = FileField('Document', validators=[
        FileRequired('Please select a file to upload.'),
        FileAllowed(
            ['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'csv', 'ppt', 'pptx'],
            'Only document files are allowed.',
        ),
    ])
    category = SelectField('Category', choices=FORM_DOCUMENT_CATEGORIES, validators=[DataRequired()])
    submit = SubmitField('Upload Document')


class PhotoUploadForm(FlaskForm):
    """Form for uploading a photo/video to an equipment record."""

    file = FileField('Photo/Video', validators=[
        FileRequired('Please select a file to upload.'),
        FileAllowed(
            ['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'mov', 'avi', 'webm'],
            'Only image and video files are allowed.',
        ),
    ])
    submit = SubmitField('Upload Photo')


class ExternalLinkForm(FlaskForm):
    """Form for adding an external link to an equipment record."""

    title = StringField('Title', validators=[DataRequired(), Length(max=200)])
    url = StringField('URL', validators=[DataRequired(), Length(max=2000), URL()])
    submit = SubmitField('Add Link')

esb/views/equipment.py
"""Equipment registry routes."""

import os

from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import current_user, login_required

from esb.forms.equipment_forms import (
    DocumentUploadForm,
    EquipmentCreateForm,
    EquipmentEditForm,
    ExternalLinkForm,
    PhotoUploadForm,
)
from esb.services import equipment_service, upload_service
from esb.utils.decorators import role_required
from esb.utils.exceptions import ValidationError

equipment_bp = Blueprint('equipment', __name__, url_prefix='/equipment')


@equipment_bp.route('/')
@login_required
def index():
    """Equipment registry list with optional area filter."""
    area_id = request.args.get('area_id', type=int)
    equipment = equipment_service.list_equipment(area_id=area_id)
    areas = equipment_service.list_areas()
    return render_template(
        'equipment/list.html',
        equipment=equipment,
        areas=areas,
        selected_area_id=area_id,
    )


@equipment_bp.route('/new', methods=['GET', 'POST'])
@role_required('staff')
def create():
    """Equipment creation form and handler."""
    form = EquipmentCreateForm()
    areas = equipment_service.list_areas()
    form.area_id.choices = [(0, '-- Select Area --')] + [
        (a.id, a.name) for a in areas
    ]

    if form.validate_on_submit():
        if form.area_id.data == 0:
            flash('Please select an area.', 'danger')
            return render_template(
                'equipment/form.html', form=form, title='Add Equipment',
            )
        try:
            eq = equipment_service.create_equipment(
                name=form.name.data,
                manufacturer=form.manufacturer.data,
                model=form.model.data,
                area_id=form.area_id.data,
                created_by=current_user.username,
                serial_number=form.serial_number.data or None,
                acquisition_date=form.acquisition_date.data,
                acquisition_source=form.acquisition_source.data or None,
                acquisition_cost=form.acquisition_cost.data,
                warranty_expiration=form.warranty_expiration.data,
                description=form.description.data or None,
            )
        except ValidationError as e:
            flash(str(e), 'danger')
            return render_template(
                'equipment/form.html', form=form, title='Add Equipment',
            )

        flash('Equipment created successfully.', 'success')
        return redirect(url_for('equipment.detail', id=eq.id))

    return render_template(
        'equipment/form.html', form=form, title='Add Equipment',
    )


@equipment_bp.route('/<int:id>')
@login_required
def detail(id):
    """Equipment detail page."""
    try:
        eq = equipment_service.get_equipment(id)
    except ValidationError:
        abort(404)

    documents = upload_service.get_documents('equipment_doc', id)
    photos = upload_service.get_documents('equipment_photo', id)
    links = equipment_service.get_equipment_links(id)
    doc_form = DocumentUploadForm()
    photo_form = PhotoUploadForm()
    link_form = ExternalLinkForm()
    can_edit_docs = _can_edit_docs() and not eq.is_archived

    return render_template(
        'equipment/detail.html',
        equipment=eq,
        documents=documents,
        photos=photos,
        links=links,
        doc_form=doc_form,
        photo_form=photo_form,
        link_form=link_form,
        can_edit_docs=can_edit_docs,
    )


@equipment_bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@role_required('staff')
def edit(id):
    """Equipment edit form and handler."""
    try:
        eq = equipment_service.get_equipment(id)
    except ValidationError:
        abort(404)

    if eq.is_archived:
        flash('Cannot edit archived equipment.', 'danger')
        return redirect(url_for('equipment.detail', id=id))

    form = EquipmentEditForm(obj=eq)
    areas = equipment_service.list_areas()
    form.area_id.choices = [(0, '-- Select Area --')] + [
        (a.id, a.name) for a in areas
    ]

    if form.validate_on_submit():
        if form.area_id.data == 0:
            flash('Please select an area.', 'danger')
            return render_template(
                'equipment/form.html', form=form, title='Edit Equipment',
            )
        try:
            equipment_service.update_equipment(
                equipment_id=id,
                updated_by=current_user.username,
                name=form.name.data,
                manufacturer=form.manufacturer.data,
                model=form.model.data,
                area_id=form.area_id.data,
                serial_number=form.serial_number.data or None,
                acquisition_date=form.acquisition_date.data,
                acquisition_source=form.acquisition_source.data or None,
                acquisition_cost=form.acquisition_cost.data,
                warranty_expiration=form.warranty_expiration.data,
                description=form.description.data or None,
            )
        except ValidationError as e:
            flash(str(e), 'danger')
            return render_template(
                'equipment/form.html', form=form, title='Edit Equipment',
            )

        flash('Equipment updated successfully.', 'success')
        return redirect(url_for('equipment.detail', id=id))

    return render_template(
        'equipment/form.html', form=form, title='Edit Equipment',
    )


@equipment_bp.route('/<int:id>/archive', methods=['POST'])
@role_required('staff')
def archive(id):
    """Archive an equipment record (soft delete)."""
    try:
        equipment_service.archive_equipment(
            equipment_id=id,
            archived_by=current_user.username,
        )
        flash('Equipment archived successfully.', 'success')
    except ValidationError as e:
        flash(str(e), 'danger')
    return redirect(url_for('equipment.detail', id=id))


def _can_edit_docs() -> bool:
    """Check if current user can edit equipment documentation.

    Staff always can. Technicians can when tech_doc_edit_enabled is 'true'.
    """
    if current_user.role == 'staff':
        return True
    if current_user.role == 'technician':
        from esb.services import config_service
        return config_service.get_config('tech_doc_edit_enabled', 'false').lower() == 'true'
    return False


def _require_doc_edit():
    """Abort 403 if current user cannot edit equipment documentation."""
    if not _can_edit_docs():
        abort(403)


# --- Document upload/delete ---


@equipment_bp.route('/<int:id>/documents', methods=['POST'])
@login_required
def upload_document(id):
    """Handle document upload for an equipment item."""
    try:
        eq = equipment_service.get_equipment(id)
    except ValidationError:
        abort(404)
    _require_doc_edit()

    if eq.is_archived:
        flash('Cannot modify archived equipment.', 'danger')
        return redirect(url_for('equipment.detail', id=id))

    form = DocumentUploadForm()
    if form.validate_on_submit():
        try:
            upload_service.save_upload(
                file=form.file.data,
                parent_type='equipment_doc',
                parent_id=id,
                uploaded_by=current_user.username,
                category=form.category.data,
            )
            flash('Document uploaded successfully.', 'success')
        except ValidationError as e:
            flash(str(e), 'danger')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'{error}', 'danger')
    return redirect(url_for('equipment.detail', id=id))


@equipment_bp.route('/<int:id>/documents/<int:doc_id>/delete', methods=['POST'])
@login_required
def delete_document(id, doc_id):
    """Delete a document from an equipment item."""
    try:
        eq = equipment_service.get_equipment(id)
    except ValidationError:
        abort(404)
    _require_doc_edit()

    if eq.is_archived:
        flash('Cannot modify archived equipment.', 'danger')
        return redirect(url_for('equipment.detail', id=id))

    try:
        upload_service.delete_upload(
            doc_id, current_user.username,
            parent_type='equipment_doc', parent_id=id,
        )
        flash('Document deleted.', 'success')
    except ValidationError as e:
        flash(str(e), 'danger')
    return redirect(url_for('equipment.detail', id=id))


# --- Photo upload/delete ---


@equipment_bp.route('/<int:id>/photos', methods=['POST'])
@login_required
def upload_photo(id):
    """Handle photo upload for an equipment item."""
    try:
        eq = equipment_service.get_equipment(id)
    except ValidationError:
        abort(404)
    _require_doc_edit()

    if eq.is_archived:
        flash('Cannot modify archived equipment.', 'danger')
        return redirect(url_for('equipment.detail', id=id))

    form = PhotoUploadForm()
    if form.validate_on_submit():
        try:
            upload_service.save_upload(
                file=form.file.data,
                parent_type='equipment_photo',
                parent_id=id,
                uploaded_by=current_user.username,
            )
            flash('Photo uploaded successfully.', 'success')
        except ValidationError as e:
            flash(str(e), 'danger')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'{error}', 'danger')
    return redirect(url_for('equipment.detail', id=id))


@equipment_bp.route('/<int:id>/photos/<int:photo_id>/delete', methods=['POST'])
@login_required
def delete_photo(id, photo_id):
    """Delete a photo from an equipment item."""
    try:
        eq = equipment_service.get_equipment(id)
    except ValidationError:
        abort(404)
    _require_doc_edit()

    if eq.is_archived:

esb/templates/equipment/detail.html
{% extends "base.html" %}

{% block title %}{{ equipment.name }} - Equipment Status Board{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('equipment.index') }}">Equipment Registry</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ equipment.name }}</li>
    </ol>
</nav>

{% if equipment.is_archived %}
<div class="alert alert-warning" role="alert">
    This equipment has been archived and is no longer active.
</div>
{% endif %}

<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>{{ equipment.name }}</h1>
    {% if not equipment.is_archived %}
    <div class="d-flex gap-2">
        <a href="{{ url_for('repairs.create', equipment_id=equipment.id) }}" class="btn btn-outline-primary btn-sm">Report Issue</a>
        {% if current_user.role == 'staff' %}
        <a href="{{ url_for('equipment.edit', id=equipment.id) }}" class="btn btn-outline-secondary">Edit</a>
        <form method="post" action="{{ url_for('equipment.archive', id=equipment.id) }}" class="d-inline">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to archive this equipment? It will be removed from active lists.')">Archive</button>
        </form>
        {% endif %}
    </div>
    {% endif %}
</div>

<div class="card mb-4">
    <div class="card-header">
        <h5 class="mb-0">Equipment Information</h5>
    </div>
    <div class="card-body">
        <dl class="row mb-0">
            <dt class="col-sm-3">Name</dt>
            <dd class="col-sm-9">{{ equipment.name }}</dd>

            <dt class="col-sm-3">Manufacturer</dt>
            <dd class="col-sm-9">{{ equipment.manufacturer }}</dd>

            <dt class="col-sm-3">Model</dt>
            <dd class="col-sm-9">{{ equipment.model }}</dd>

            <dt class="col-sm-3">Area</dt>
            <dd class="col-sm-9">{{ equipment.area.name }}</dd>
        </dl>
    </div>
</div>

{% if equipment.serial_number or equipment.acquisition_date or equipment.acquisition_source or equipment.acquisition_cost is not none or equipment.warranty_expiration or equipment.description %}
<div class="card mb-4">
    <div class="card-header">
        <h5 class="mb-0">Additional Details</h5>
    </div>
    <div class="card-body">
        <dl class="row mb-0">
            {% if equipment.serial_number %}
            <dt class="col-sm-3">Serial Number</dt>
            <dd class="col-sm-9">{{ equipment.serial_number }}</dd>
            {% endif %}

            {% if equipment.acquisition_date %}
            <dt class="col-sm-3">Acquisition Date</dt>
            <dd class="col-sm-9">{{ equipment.acquisition_date|format_date }}</dd>
            {% endif %}

            {% if equipment.acquisition_source %}
            <dt class="col-sm-3">Acquisition Source</dt>
            <dd class="col-sm-9">{{ equipment.acquisition_source }}</dd>
            {% endif %}

            {% if equipment.acquisition_cost is not none %}
            <dt class="col-sm-3">Acquisition Cost</dt>
            <dd class="col-sm-9">${{ "%.2f"|format(equipment.acquisition_cost) }}</dd>
            {% endif %}

            {% if equipment.warranty_expiration %}
            <dt class="col-sm-3">Warranty Expiration</dt>
            <dd class="col-sm-9">{{ equipment.warranty_expiration|format_date }}</dd>
            {% endif %}

            {% if equipment.description %}
            <dt class="col-sm-3">Description</dt>
            <dd class="col-sm-9">{{ equipment.description }}</dd>
            {% endif %}
        </dl>
    </div>
</div>
{% endif %}

{# --- Documents Section --- #}
<div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Documents</h5>
        {% if can_edit_docs %}
        <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#upload-doc-form">
            Upload Document
        </button>
        {% endif %}
    </div>
    <div class="card-body">
        {% if can_edit_docs %}
        <div class="collapse mb-3" id="upload-doc-form">
            <form method="post" action="{{ url_for('equipment.upload_document', id=equipment.id) }}" enctype="multipart/form-data">
                {{ doc_form.hidden_tag() }}
                <div class="row g-2 align-items-end">
                    <div class="col-12 col-md-5">
                        <label for="{{ doc_form.file.id }}" class="form-label">File *</label>
                        {{ doc_form.file(class="form-control") }}
                    </div>
                    <div class="col-12 col-md-4">
                        <label for="{{ doc_form.category.id }}" class="form-label">Category *</label>
                        {{ doc_form.category(class="form-select") }}
                    </div>
                    <div class="col-12 col-md-3">
                        {{ doc_form.submit(class="btn btn-primary w-100") }}
                    </div>
                </div>
            </form>
        </div>
        {% endif %}

        {% if documents %}
        <div class="list-group">
            {% for doc in documents %}
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    {% if doc.category %}
                    <span class="badge bg-secondary me-2">{{ doc.category|category_label }}</span>
                    {% endif %}
                    <a href="{{ url_for('equipment.serve_document', id=equipment.id, filename=doc.stored_filename) }}">
                        {{ doc.original_filename }}
                    </a>
                    <small class="text-muted ms-2">
                        {{ doc.size_bytes|filesize }}
                        &middot; {{ doc.uploaded_by }}
                        &middot; {{ doc.created_at.strftime('%Y-%m-%d') }}
                    </small>
                </div>
                {% if can_edit_docs %}
                <form method="post" action="{{ url_for('equipment.delete_document', id=equipment.id, doc_id=doc.id) }}" class="d-inline">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure you want to delete this document?')">Delete</button>
                </form>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p class="text-muted text-center mb-0">No documents attached yet.</p>
        {% endif %}
    </div>
</div>

{# --- Photos Section --- #}
<div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Photos</h5>
        {% if can_edit_docs %}
        <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#upload-photo-form">
            Upload Photo
        </button>
        {% endif %}
    </div>
    <div class="card-body">
        {% if can_edit_docs %}
        <div class="collapse mb-3" id="upload-photo-form">
            <form method="post" action="{{ url_for('equipment.upload_photo', id=equipment.id) }}" enctype="multipart/form-data">
                {{ photo_form.hidden_tag() }}
                <div class="row g-2 align-items-end">
                    <div class="col-12 col-md-9">
                        <label for="{{ photo_form.file.id }}" class="form-label">Photo/Video *</label>
                        {{ photo_form.file(class="form-control") }}
                    </div>
                    <div class="col-12 col-md-3">
                        {{ photo_form.submit(class="btn btn-primary w-100") }}
                    </div>
                </div>
            </form>
        </div>
        {% endif %}

        {% if photos %}
        <div class="row g-3">
            {% for photo in photos %}
            <div class="col-6 col-md-4 col-lg-3">
                <div class="card h-100">
                    {% set ext = photo.original_filename.rsplit('.', 1)[-1].lower() %}
                    {% if ext in ['jpg', 'jpeg', 'png', 'gif', 'webp'] %}
                    <img src="{{ url_for('equipment.serve_photo', id=equipment.id, filename=photo.stored_filename) }}"
                         class="card-img-top" alt="{{ photo.original_filename }}"
                         style="max-height: 200px; object-fit: cover;">
                    {% else %}
                    <div class="card-img-top d-flex align-items-center justify-content-center bg-light" style="height: 200px;">
                        <span class="text-muted fs-1">&#128249;</span>
                    </div>
                    {% endif %}
                    <div class="card-body p-2">
                        <small class="text-truncate d-block">{{ photo.original_filename }}</small>
                        <small class="text-muted d-block">
                            {{ photo.size_bytes|filesize }}
                            &middot; {{ photo.uploaded_by }}
                            &middot; {{ photo.created_at.strftime('%Y-%m-%d') }}
                        </small>
                        {% if can_edit_docs %}
                        <form method="post" action="{{ url_for('equipment.delete_photo', id=equipment.id, photo_id=photo.id) }}" class="mt-1">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-outline-danger btn-sm w-100" onclick="return confirm('Are you sure you want to delete this photo?')">Delete</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p class="text-muted text-center mb-0">No photos attached yet.</p>
        {% endif %}
    </div>
</div>

{# --- Links Section --- #}
<div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Links</h5>
        {% if can_edit_docs %}
        <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#add-link-form">
            Add Link
        </button>
        {% endif %}
    </div>
    <div class="card-body">
        {% if can_edit_docs %}
        <div class="collapse mb-3" id="add-link-form">
            <form method="post" action="{{ url_for('equipment.add_link', id=equipment.id) }}">
                {{ link_form.hidden_tag() }}
                <div class="row g-2 align-items-end">
                    <div class="col-12 col-md-4">
                        <label for="{{ link_form.title.id }}" class="form-label">Title *</label>
                        {{ link_form.title(class="form-control", placeholder="Link title") }}
                    </div>
                    <div class="col-12 col-md-5">
                        <label for="{{ link_form.url.id }}" class="form-label">URL *</label>
                        {{ link_form.url(class="form-control", placeholder="https://...") }}
                    </div>
                    <div class="col-12 col-md-3">
                        {{ link_form.submit(class="btn btn-primary w-100") }}
                    </div>
                </div>
            </form>
        </div>
        {% endif %}

        {% if links %}
        <div class="list-group">
            {% for link in links %}
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <a href="{{ link.url }}" target="_blank" rel="noopener noreferrer">{{ link.title }}</a>
                    <small class="text-muted ms-2">
                        {{ link.created_by }}
                        &middot; {{ link.created_at.strftime('%Y-%m-%d') }}
                    </small>
                </div>
                {% if can_edit_docs %}
                <form method="post" action="{{ url_for('equipment.delete_link', id=equipment.id, link_id=link.id) }}" class="d-inline">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure you want to delete this link?')">Delete</button>
                </form>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p class="text-muted text-center mb-0">No links added yet.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

esb/templates/equipment/list.html
{% extends "base.html" %}

{% block title %}Equipment Registry - Equipment Status Board{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Equipment Registry</h1>
    {% if current_user.role == 'staff' %}
    <a href="{{ url_for('equipment.create') }}" class="btn btn-primary">Add Equipment</a>
    {% endif %}
</div>

<form method="GET" action="{{ url_for('equipment.index') }}" class="mb-3">
    <div class="row align-items-end">
        <div class="col-auto">
            <label for="area_id" class="form-label">Filter by Area</label>
            <select name="area_id" id="area_id" class="form-select" onchange="this.form.submit()">
                <option value="">All Areas</option>
                {% for area in areas %}
                <option value="{{ area.id }}" {% if selected_area_id == area.id %}selected{% endif %}>{{ area.name }}</option>
                {% endfor %}
            </select>
        </div>
        {% if selected_area_id %}
        <div class="col-auto">
            <a href="{{ url_for('equipment.index') }}" class="btn btn-outline-secondary">Clear Filter</a>
        </div>
        {% endif %}
    </div>
</form>

{% if equipment %}
<!-- Desktop table (hidden on mobile) -->
<div class="table-responsive d-none d-md-block">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Manufacturer</th>
                <th>Model</th>
                <th>Area</th>
            </tr>
        </thead>
        <tbody>
            {% for eq in equipment %}
            <tr>
                <td><a href="{{ url_for('equipment.detail', id=eq.id) }}">{{ eq.name }}</a></td>
                <td>{{ eq.manufacturer }}</td>
                <td>{{ eq.model }}</td>
                <td>{{ eq.area.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Mobile cards (hidden on desktop) -->
<div class="d-md-none">
    {% for eq in equipment %}
    <a href="{{ url_for('equipment.detail', id=eq.id) }}" class="text-decoration-none text-dark">
        <div class="card mb-2">
            <div class="card-body">
                <h6 class="card-title mb-1">{{ eq.name }}</h6>
                <p class="card-text text-muted mb-1">{{ eq.manufacturer }} {{ eq.model }}</p>
                <span class="badge bg-secondary">{{ eq.area.name }}</span>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
{% elif selected_area_id %}
<div class="text-center py-5">
    <p class="text-muted mb-3">No equipment found in this area.</p>
    <a href="{{ url_for('equipment.index') }}" class="btn btn-outline-secondary">Clear Filter</a>
</div>
{% else %}
<div class="text-center py-5">
    <p class="text-muted mb-3">No equipment has been added yet.</p>
    {% if current_user.role == 'staff' %}
    <a href="{{ url_for('equipment.create') }}" class="btn btn-primary">Add Equipment</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}